//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamResults
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public int studentId { get; set; }
        public Nullable<int> ApplicationNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> SecurityPin { get; set; }
        public string cachepin { get; set; }
    }
}
